// This is a hack
// Loading JSON is finicky even now
// But loading a plain JS object to a global var is fine!

const data = {
    "action": {
      title: ["Collapse", "Discipline", "Grow", "Transform"], 
      timeline: [
      "A few years",
      "A decade",
      "30 years",
      "60 years"
    ]},
      "topic": [
        "Agriculture",
        "The Brain",
        "Childhood",
        "Citizenship",
        "Class",
        "Climate",
        "Cloning",
        "Communications",
        "Court",
        "Disease",
        "The Economy",
        "Drones",
        "The Economy",
        "Entertainment",
        "Environment",
        "Equality",
        "Family",
        "Fashion",
        "Flight",
        "Forests",
        "Genetics",
        "Gender",
        "Governance",
        "Health",
        "Hobbies",
        "Home",
        "Identity",
        "Insects",
        "Intellectual Property",
        "Journalism",
        "Justice",
        "Learning",
        "Memory",
        "Mining",
        "The Moon",
        "Music",
        "Oceans",
        "Oil",
        "Old Age",
        "Pets",
        "Power",
        "Religion",
        "Robots",
        "Sex",
        "Shopping",
        "Space",
        "Sports",
        "Theatre",
        "Travel",
        "War",
        "Water",
        "Wealth",
        "Women",
        "Work",
        "Zombies",
        "The Zoo"
      ],
      "object": [
        "Advertisement",
        "Artwork",
        "Beverage",
        "Book",
        "Bottle",
        "Box",
        "Brochure",
        "Building",
        "Candy",
        "Clothing",
        "Corporation",
        "Device",
        "Document",
        "Event",
        "Festival",
        "Flag",
        "Game",
        "Gift",
        "Headline",
        "Implant",
        "Instrument",
        "Jewellery",
        "Kit",
        "Law",
        "Logo",
        "Lotion",
        "Machine",
        "Magazine cover",
        "Map",
        "Mask",
        "Monument",
        "Passport",
        "Pill",
        "Plant",
        "Postcard",
        "Poster",
        "Product",
        "Prosthetic",
        "Public service announcement",
        "Relic",
        "Ritual",
        "Show",
        "Slogan",
        "Snack",
        "Song",
        "Souvenir",
        "Statue",
        "Sticker",
        "Symbol",
        "T-Shirt",
        "Tattoo",
        "Tool",
        "Toy",
        "Vehicle",
        "Video",
        "Weapon"
      ],
      "mood": [
        "Admiration",
        "Alienation",
        "Amusement",
        "Anger",
        "Anxiety",
        "Awkwardness",
        "Calm",
        "Charm",
        "Cheer",
        "Contentment",
        "Curiosity",
        "Decadence",
        "Delight",
        "Dignity",
        "Disgust",
        "Dread",
        "Embarrassment",
        "Excitement",
        "Exhilaration",
        "Fascination",
        "Fervor",
        "Frustration",
        "Gratitude",
        "Happiness",
        "Hilarity",
        "Hope",
        "Longing",
        "Malaise",
        "Melancholy",
        "Melodrama",
        "Nostalgia",
        "Optimism",
        "Outrage",
        "Pathos",
        "Pleasure",
        "Pride",
        "Rationality",
        "Relief",
        "Resentment",
        "Respect",
        "Sadness",
        "Satisfaction",
        "Serenity",
        "Shame",
        "Shock",
        "Sorrow",
        "Surprise",
        "Unease",
        "Warmth",
        "Weirdness",
        "Wellbeing",
        "Wonder",
        "Worry",
        "Zen"
      ]

}